name: Detect outdated dependencies (pnpm)

on:
  # 00:00 JST (金曜) ＝ 前日 15:00 UTC (木曜)
  schedule:
    - cron: '0 15 * * 4'
  workflow_dispatch:

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm -r install --frozen-lockfile

      - name: Check for outdated packages
        run: pnpm -r outdated
